export const payments = [
  {
    date: "12.12.2023 18:24",
    fullname: "Cuvilliez Philippe",
    attribution: "Torti Thierry (Manager)",
    plan: "HSBC Free Booklet",
    price: "1,100.00 EUR",
    bonuses: "0.0%",
    payment: true,
  },
  {
    date: "12.12.2023 18:24",
    fullname: "Cuvilliez Philippe",
    attribution: "Torti Thierry (Manager)",
    plan: "HSBC Free Booklet",
    price: "1,100.00 EUR",
    bonuses: "0.0%",
    payment: true,
  },
  {
    date: "12.12.2023 18:24",
    fullname: "Cuvilliez Philippe",
    attribution: "Torti Thierry (Manager)",
    plan: "HSBC Free Booklet",
    price: "1,100.00 EUR",
    bonuses: "0.0%",
    payment: true,
  },
  {
    date: "12.12.2023 18:24",
    fullname: "Cuvilliez Philippe",
    attribution: "Torti Thierry (Manager)",
    plan: "HSBC Free Booklet",
    price: "1,100.00 EUR",
    bonuses: "0.0%",
    payment: true,
  },
  {
    date: "12.12.2023 18:24",
    fullname: "Cuvilliez Philippe",
    attribution: "Torti Thierry (Manager)",
    plan: "HSBC Free Booklet",
    price: "1,100.00 EUR",
    bonuses: "0.0%",
    payment: true,
  },
];
